name: Update Submodules

on:
  workflow_dispatch:
    

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Update parent submodule
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git submodule update --remote --merge
          git add .
          git commit -m "Updated submodule references"
          git push
